// This file holds all action types.

export const COMPLETE_ONBOARDING = 'COMPLETE_ONBOARDING';
export const RESET_ONBOARDING = 'RESET_ONBOARDING';

export const SET_HOTLINE_NAME = 'SET_HOTLINE_NAME';
export const SET_HOTLINE_NUMBER = 'SET_HOTLINE_NUMBER';

export const TOGGLE_ICE_NOTIFICATIONS = 'TOGGLE_ICE_NOTIFICATIONS';
export const TOGGLE_DEFAULT_NOTIFICATIONS = 'TOGGLE_DEFAULT_NOTIFICATIONS';
