// This file holds all action types.

export const COMPLETE_ONBOARDING = 'COMPLETE_ONBOARDING';
export const RESET_ONBOARDING = 'RESET_ONBOARDING';

export const SET_HOTLINE_NAME = 'SET_HOTLINE_NAME';
export const SET_HOTLINE_NUMBER = 'SET_HOTLINE_NUMBER';

export const SET_ANNOUNCEMENTS = 'SET_ANNOUNCEMENTS';
export const SET_ARREST_ALERTS = 'SET_ARREST_ALERTS';
export const SET_EVENT_ALERTS = 'SET_EVENT_ALERTS';
